name: Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v5.4.0
      with:
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install -e .[dev]
        # Verify installation
        python -c "import AutoFeedback; print(AutoFeedback.__version__)"
    - name: Build and Deploy Pages
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs/source