name: Pages
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v5.4.0
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Install Dependencies
      run : |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
        pip install .
    - name: Build and Commit
      id: deployment
      uses: sphinx-notes/pages@v3.2
      with:
        documentation_path: ./docs
        publish: false
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ steps.deployment.outputs.artifact }}
        branch: gh-pages
